name: help wanted solve🧩
description: solve something problematic
title: help wanted solve
labels: 'help wanted solve'
assignees:
  - steve02081504
body:
  - type: textarea
    id: name
    attributes:
      label: "想要解决的问题\nName of hw"
      description: 写下其名称
    validations:
      required: true
  - type: textarea
    id: time
    attributes:
      label: "所需时间\nTime required"
      description: 你需要的时间
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: "附注\nNotes"
      description: 其他什么
